// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings to SileroVadLibrary
class SileroVadLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SileroVadLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SileroVadLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  VadHandle create_vad(
    ffi.Pointer<ffi.Char> model_path,
    int sample_rate,
    int frame_size,
    double threshold,
    int min_silence_duration_ms,
    int speech_pad_ms,
  ) {
    return _create_vad(
      model_path,
      sample_rate,
      frame_size,
      threshold,
      min_silence_duration_ms,
      speech_pad_ms,
    );
  }

  late final _create_vadPtr = _lookup<
      ffi.NativeFunction<
          VadHandle Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int, ffi.Float,
              ffi.Int, ffi.Int)>>('create_vad');
  late final _create_vad = _create_vadPtr.asFunction<
      VadHandle Function(ffi.Pointer<ffi.Char>, int, int, double, int, int)>();

  int predict(
    VadHandle handle,
    ffi.Pointer<ffi.Float> data,
    int data_length,
  ) {
    return _predict(
      handle,
      data,
      data_length,
    );
  }

  late final _predictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              VadHandle, ffi.Pointer<ffi.Float>, ffi.Int)>>('predict');
  late final _predict = _predictPtr
      .asFunction<int Function(VadHandle, ffi.Pointer<ffi.Float>, int)>();

  void destroy_vad(
    VadHandle handle,
  ) {
    return _destroy_vad(
      handle,
    );
  }

  late final _destroy_vadPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VadHandle)>>('destroy_vad');
  late final _destroy_vad =
      _destroy_vadPtr.asFunction<void Function(VadHandle)>();
}

typedef VadHandle = ffi.Pointer<ffi.Void>;
